### ISSUE TITLE
Disable checks for production code

### ISSUE THREAD

**Issue by sobolevn** [aeirola/io-ts-promise#8]
Hi, thanks for this library! 

Is it possible to disable runtime checks in production? Like when `NODE_ENV=='production'`?

**Comment by sobolevn** [comment]
Btw, I have included your library to our template. Check it out: https://github.com/wemake-services/wemake-vue-template/blob/master/template/client/logic/comments/services/api.ts

**Comment by aeirola** [comment]
Hi, and thanks for your interest in the library. io-ts-promise itself doesn't perform the runtime type checks, it just provides helpers for the underlying [io-ts](https://github.com/gcanti/io-ts) library. So in order to disable runtime checks in production, you would want to do that on the io-ts level. There is some discussion about this in the readme at https://github.com/gcanti/io-ts#is-there-a-way-to-turn-the-checks-off-in-production-code.

I don't think it would fit in the scope of this library to start provide helpers for configuring runtime checks for production environments either. It might be a good idea for a separate library though. Closing the ticket as this isn't something that would be implemented in this library.
